/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CalcJNI */

#ifndef _Included_CalcJNI
#define _Included_CalcJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CalcJNI
 * Method:    doCalculate
 * Signature: (IIC)V
 */
JNIEXPORT void JNICALL Java_CalcJNI_doCalculate
  (JNIEnv *, jobject, jint, jint, jchar);

#ifdef __cplusplus
}
#endif
#endif
