/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EvenOddJNI */

#ifndef _Included_EvenOddJNI
#define _Included_EvenOddJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EvenOddJNI
 * Method:    Determine
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_EvenOddJNI_Determine
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
