trial <- read.csv("/home/student/Downloads/iris.csv")
head(trial)
summary(trial)
summary(trial$sepal_length)
summary(trial$sepal_width)
summary(trial$petal_length)
summary(trial$petal_width)
sd(trial$sepal_length)
sd(trial$sepal_width)
sd(trial$petal_length)
sd(trial$petal_width)
boxplot(sepal_length ~ sepal_width,data = trial, xlab = "width", ylab = "length",main = "Sepal Data")
boxplot(petal_length ~ petal_width,data = trial, xlab = "width", ylab = "length",main = "Petal Data") 
boxplot(trial$petal_length,data = trial, xlab = "", ylab = "Length",main = "Petal Length")
boxplot(trial$petal_width,data = trial, xlab = "", ylab = "Width",main = "Petal Width") 
virginica <- subset(trial, species == "virginica", select = c(petal_length,petal_width))
boxplot(main = "Petal length and width in virginca species",virginica$petal_length~virginica$petal_width, xlab="Width", ylab="Length")
setosa <- subset(trial, species == "setosa", select = c(petal_length,petal_width))
boxplot(main = "Petal length and width in setosa species",setosa$petal_length~setosa$petal_width, xlab="Width", ylab="Length")
versicolor <- subset(trial, species == "versicolor", select = c(petal_length,petal_width))
